### ISSUE TITLE
Migrate: `pnpm` over `npm`

### ISSUE THREAD

**Issue by pegahcarter** [FraxFinance/frax-template#8]
Very simple.  Upgrade our package manager from the old npm to [pnpm](https://pnpm.io)

**Comment by naftalimurgor** [comment]
Hey, I'd like to work on this. Seems fun to work on.

**Comment by pegahcarter** [comment]
@naftalimurgor great!  I will tag you when we're ready to have a PR submitted and give you the spec.  We are working on other dependencies that will impact this PR.

**Comment by pegahcarter** [comment]
@naftalimurgor All is good to go ahead :+1:

**Comment by naftalimurgor** [comment]
@pegahcarter 

sure thing! 

Submitting a WIP PR to set the ball rolling :rocket:
